### ISSUE TITLE
Fix the Bash-ness of the Bash script

### ISSUE THREAD

**Issue by Beep6581** [jomo/imgur-screenshot#101]
Hello

The script is called `imgur-screenshot.sh` which means that it is a shell script, but begins with `#!/bin/bash` which means that it is a Bash script. That is inconsistent, and `#!/bin/bash` is less portable because the `bash` executable does not necessarily have to be in `/bin/`. A better shebang could be `#!/usr/bin/env bash` so that it finds the `bash` executable by searching in `$PATH`.

Further, the external test command `[` is used instead of using the Bash keyword `[[`.

Is this something you deem worth changing? I could do that if you do.

Kind regards

References:
See "Builtins", "Keywords" and "Executables" here: http://mywiki.wooledge.org/BashGuide/CommandsAndArguments#Builtins
http://mywiki.wooledge.org/BashFAQ/031

**Comment by jomo** [comment]
I have some local changes yet to be pushed where I already switched to /usr/bin/env.

According to the bash manual, `[` and `test` are both **builtin** commands (and `[[` is a compound command).

Thanks for reporting!
