### ISSUE TITLE
Create a PPA for easy installation

### ISSUE THREAD

**Issue by khurshid-alam** [jomo/imgur-screenshot#106]
A ppa or deb would be nice. If you need help I can help you with that. Thanks.

**Comment by jomo** [comment]
I agree it would be nice to have. The packages available through Homebrew, AUR, COPR, Nix, etc are all maintained by other users / the community.

Feel free to create a PPA if you want to (or anyone else), I'll add it to the README!

**Comment by khurshid-alam** [comment]
@jomo Sorry for late reply. Only thing preventing me from creating ppa is `.sh` extension. `.sh` can not go in `/usr/bin`. If you remove .sh and update I can create a PPA

**Comment by jomo** [comment]
I will consider this for the future. Would it be possible to create a symlink in `/usr/bin/` for now?
