### ISSUE TITLE
Crash on i3 restart

### ISSUE THREAD

**Issue by rhssk** [jomo/imgur-screenshot#107]
This may very well be an issue with i3 itself but I'd like to hear your input anyways before(if) submitting report for i3.

Debug log when running imgur-screenshot from command line: https://hastebin.com/ocuhetixam.php
Debug log when running imgur-screenshot using keybindings: https://hastebin.com/edusukegap.coffeescript

When I run the command by using keybinding defined in i3config:
`bindsym --release Shift+Ctrl+Print exec "imgur-screenshot --debug"`
I get the notification with imgur link but for some reason xdg-open doesn't get executed. Also there is some gibberish at the end of debug log. Some times when I restart i3 in place after executing imgur-screenshot with keybindings i3 completely freezes and I have to kill it manually from different TTY.
Here's my config file: https://hastebin.com/iposeqavol.ini

Any ideas?

**Comment by jomo** [comment]
The "gibberish" is actually ANSI escape codes. After applying them you get this prompt:
![screenshot](https://i.imgur.com/pJFKRcq.png)

[Searching](https://github.com/search?q=%22Content+type+is%22+%22Do+you+want+to+save+or+display+this+file%3F%22&type=Code&utf8=%E2%9C%93) for the text suggests this is coming from Links or eLinks. So xdg-open *does* get executed and runs said program. Unfortunately there's no standard behavior of [xdg-open](https://unix.stackexchange.com/questions/144047/how-does-xdg-open-do-its-work#144048), but my best guess is your implementation uses different programs to open HTTP links depending on the shell/environment it runs in.

**Comment by rhssk** [comment]
Indeed, I check if there is $DISPLAY variable available and depending on that I set my $BROWSER to either chromium or links. Thanks
