### ISSUE TITLE
Borders everywhere

### ISSUE THREAD

**Issue by qwemaze** [jomo/imgur-screenshot#108]
1. $ imgur-screenshot
2. draw reclangle
3. borders stay and flicker

```
$ imgur-screenshot -u
Version v1.7.4 is up to date.

$ imgur-screenshot --check
OK: found grep
OK: found notify-send
OK: found scrot
OK: found xclip
OK: found curl

$ uname -a
Linux umaze-epam 4.8.0-46-generic #49~16.04.1-Ubuntu SMP Fri Mar 31 14:51:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
![heyyyy lmao](https://i.imgur.com/WXfWWDM.png)

**Comment by jomo** [comment]
This is a known issue of scrot, which has been unmaintained for nearly 14 years. You can configure a different tool to take screenshots.

**Comment by Tithen-Firion** [comment]
Some alternatives can be found here: #32
