### ISSUE TITLE
Annotation Feature Before Upload

### ISSUE THREAD

**Issue by defencedog** [jomo/imgur-screenshot#109]
An annotation feature before upload will be highly useful ..not much say arrows, text, rectangle will suffice

**Comment by jomo** [comment]
Sorry, must have missed this issue. You can already do this using whichever editor you prefer by setting the `edit_command` configuration or using the `-i` / `--edit-command` args.

**Comment by defencedog** [comment]
sir sorry ..but how do I use it
In my terminal I invoked
`imgurshot -i viewnior`
but viewnior opened blank (terminal did said after select area ...opening editor). Can you please make a more comprehensive answer

**Comment by jomo** [comment]
You probably need to include the image filename using `%img`, see [the documentation](https://github.com/jomo/imgur-screenshot/wiki/Config)
