### ISSUE TITLE
Command flags for actually taking screenshots are undocumented

### ISSUE THREAD

**Issue by hopibel** [jomo/imgur-screenshot#110]
Running `imgur-screenshot -h` does not list the `-s`, `-w`, and `-f` flags for selection, window, and fullscreen screenshots. I had to check the source to actually figure out how to use this, which is a bit absurd considering that taking screenshots is one of the program's main functions.

**Comment by abcarroll** [comment]
You could always submit a patch

**Comment by jomo** [comment]
There is a PR addressing this, actually (just closed by the author). I'm halfway through cleaning up the whole project, fixing most if not all the currently open issues and PRs, including this one. I just need to get it done. ETA soonish™

**Comment by jomo** [comment]
Fixed in fc8c74e
