### ISSUE TITLE
failed on gnome3 

### ISSUE THREAD

**Issue by killajoe** [jomo/imgur-screenshot#112]
i can use it from terminal with no issue but try to use it over menu (.desktop entry) it failes and give only notification : something went wrong :(

**Comment by jomo** [comment]
First guess would be that one of the dependencies aren't in your `$PATH`.

You can also try running `imgur-screenshot --debug > ~/debug.log 2>&1` in your .desktop file to get more information.

**Comment by killajoe** [comment]
if i use `imgur-screenshot --debug` as command for the .desktop file it is working as it should do ...
here is my imgur-screenshot.desktop:
```
[Desktop Entry]
Version=1.0
Type=Application
Name=imgur-screenshot
Comment=Upload the image to imgur web service
Exec=imgur-screenshot --debug
Icon=/usr/share/icons/Numix-Circle/48/apps/accessories-screenshot.svg
MimeType=image/png;image/jpeg;image/bmp;image/gif;image/tiff;image/xcf
Categories=Graphics;Network;
OnlyShowIn=GNOME;
Terminal=false
Hidden=false
```

**Comment by jomo** [comment]
The same thing fails when you use `Exec=imgur-screenshot`?

**Comment by killajoe** [comment]
https://i.imgur.com/hdAmJpB.png
https://i.imgur.com/SGcGy8x.png
yes as you can see here (failed shot was taken manual with gnome-screenshot ;) )

**Comment by jomo** [comment]
I suppose it fails due to pressing a key or mouse button (from opening the desktop file) at the same time it's trying to capture a screen selection. The debug flag might cause it to run slightly slower so it's not happening. Can you try adding some delay such as `sleep 3` before it runs?

That would be `Exec=sleep 3; imgur-screenshot`, if the desktop entry supports that.

**Comment by killajoe** [comment]
So with a bash-wrapper (i do not know if this is in any way the right term)
with imgur.sh
```
#/bin/bash
sleep 3 && imgur-screenshot
```
and change the **exec=imgur.sh** inside .desktop file semms to work ;)

**Comment by jomo** [comment]
Thanks for the update. I'll close this, as it's not an issue of imgur-screenshot itself.
You could also try setting `screenshot_select_command` to something like `"sleep x; scrot -s %img"` in the configuration file.
