### ISSUE TITLE
Length of notification shown for `notify-send` is WAY too short.

### ISSUE THREAD

**Issue by RyanSquared** [jomo/imgur-screenshot#113]
I could barely even see the notification in half a second. Personally, I say bump it up to 2500 MS.

**Comment by RyanSquared** [comment]
This may be related to #80 - I think by default it should be longer, but also be configurable.

**Comment by Architector4** [comment]
I think the notify time shouldn't even be set, and left up to the notification daemon to decide, likely based on how the user configured it.
