### ISSUE TITLE
Allow configuration of the clipboard command on Linux

### ISSUE THREAD

**Issue by namtabmai** [jomo/imgur-screenshot#115]
Just been playing with this util and wasn't getting the imgur url of the upload into my clipboard and it took me a while to figure out why.

Currently you have hard coded

`xclip -selection clipboard
`

Admittedly [clipboards](https://wiki.archlinux.org/index.php/clipboard) on Linux are a bit weird, but really you shouldn't be forcing the option of "-selection clipboard" here as it overrides what people might have configured in the .XResource

Either leave this blank so the defaults kick in and people can override as they would expect of xclip, or make the clipboard ( and parameters ) configurable.

**Comment by jomo** [comment]
Sounds good, will add this in the next version.

**Comment by sorezzz** [comment]
yea!
