### ISSUE TITLE
Black screenshot

### ISSUE THREAD

**Issue by romeozi** [jomo/imgur-screenshot#118]
All the screenshots are compltely black.

I'm Using Ubuntu 17.10

**Comment by Brottweiler** [comment]
What screenshot program do you use? Scrot? What if you use it by itself, outside of imgur-screenshot, are they still black?

**Comment by romeozi** [comment]
I'm using imgur-screenshot itself. When the image is uploaded is completely black (eg. https://i.imgur.com/ukzipNG.png)

**Comment by Brottweiler** [comment]
What if you use scrot by itself, still black?

**Comment by jomo** [comment]
This is not a bug in imgur-screenshot in any case, as it doesn't do the actual screenshots. AFAIK Ubuntu 17.10 ships with Wayland, which is not supported by scrot. You need to configure a screenshot capturing tool that supports wayland, such as gnome-screenshot.

There's an open PR (#114) that will detect wayland autimatically, which I will merge (as it is that or in a similar fashion) soon™️.

Until then, please edit your config as shown in the PR:

https://github.com/jomo/imgur-screenshot/blob/511ec3f9b8a9aabc46c8f78611231ba53f413023/imgur-screenshot.sh#L57-L59
