### ISSUE TITLE
Error 400 on every file

### ISSUE THREAD

**Issue by ValdikSS** [jomo/imgur-screenshot#119]
Hi, for about a month from now this script stopped working.
File upload procedure to https://api.imgur.com/3/image always returns 400. Deleting credentials.conf does not help.
Am I the only who have this issue or APIv3 is totally deprecated and no longer working?

**Comment by jomo** [comment]
Did a fresh master clone myself, everything works for anonymous uploads. Do you have a custom `imgur_anon_id` in your settings?

I do get the 403 for authorized uploads, though:

```json
{
  "data": {
    "error": "The access token provided is invalid.",
    "request": "/3/image",
    "method": "POST"
  },
  "success": false,
  "status": 403
}
```

I will have to take a closer look later on. Perhaps recreating / reauthenticating the app helps?

**Comment by ValdikSS** [comment]
It seems something is wrong with my account. Upload functionality does not work even in browser when being logged in, while works fine without account. Sent message to imgur about that.

**Comment by jomo** [comment]
Also can't upload to my account on their website. Getting 403 from `https://imgur.com/upload/checkcaptcha` and then nothing happens
