### ISSUE TITLE
Copr repository fails to sync for f27

### ISSUE THREAD

**Issue by 0xMatt** [jomo/imgur-screenshot#120]
Even though it's listed as available the repo fails to sync for f27. I have to set the releasever to 26 to actually download the package.

**Comment by jomo** [comment]
Sorry, I don't maintain any repositores. Are you talking about this one: https://copr.fedorainfracloud.org/coprs/valdikss/imgur-screenshot/
Looks like @ValdikSS is maintaining it?

**Comment by ValdikSS** [comment]
@0xMatt, reuploaded the package, should be available for F27 now.

**Comment by 0xMatt** [comment]
Repo synchronizes now, thanks for the prompt resolution @ValdikSS!
