### ISSUE TITLE
Graphical issue on screen capture window?

### ISSUE THREAD

**Issue by KevinTyrrell** [jomo/imgur-screenshot#121]
imgur-screenshot was updated, all dependencies are located. 

When I call it from the command line by typing `imgur-screenshot`, on my blank desktop it will work perfectly. Unfortunately if I have another window open and it is dragged over the window, graphical issues like the one shown below will occur. I get an output of: 

`[5393:5437:1228/185506.005439:ERROR:browser_gpu_channel_host_factory.cc(107)] Failed to launch GPU process.
Created new window in existing browser session.`

![](https://i.imgur.com/UZcssf9.png)

If I try to run it through my application view, this happens: 

![screenshot from 2017-12-28 18-58-37](https://user-images.githubusercontent.com/12791400/34426139-356f8180-ec01-11e7-8c26-188faffbe4ea.png)

**Comment by milandamen** [comment]
@KevinTyrrell for the graphical issue, use a different screenshot tool as described in https://github.com/jomo/imgur-screenshot/issues/32. Personally I use Maim and this configuration: `screenshot_select_command="maim -s %img --hidecursor"`
