### ISSUE TITLE
AUR version 1.7.4 not working properly

### ISSUE THREAD

**Issue by jcavejr** [jomo/imgur-screenshot#123]
The AUR has 1.7.4 which after taking a screenshot continuously tries to open a window in error. Only got it to stop by uninstalling it, couldn't even find a process to kill to stop it.

**Comment by jomo** [comment]
Can you explain "continuously tries to open a window in error"?
Also, could you review your `open_command` and `edit_command` [configuration](https://github.com/jomo/imgur-screenshot/wiki/Config)?
