### ISSUE TITLE
[feature request] Ability to change mode by additional command line parameter

### ISSUE THREAD

**Issue by zhartus** [jomo/imgur-screenshot#129]
It will be great if user can change the mode not only in the config file, but also by adding the parameter in the command line. Examples:
```
imgur-screenshot.sh -m select
imgur-screenshot.sh -m window
imgur-screenshot.sh -m full
```

**Comment by Tithen-Firion** [comment]
It's already done: https://github.com/jomo/imgur-screenshot/blob/6a4433a02916d635890a72a84ea753ba6b4cf56c/imgur-screenshot.sh#L416-L423
Just not documented.

**Comment by zhartus** [comment]
Wow! Thank you, it's amazing.
