### ISSUE TITLE
Missing response_type=pin in requests

### ISSUE THREAD

**Issue by oblitum** [jomo/imgur-screenshot#133]
When `imgur-screenshot` makes a request asking back for the PIN, it doesn't send a request with `response_type=pin` in it, so the user is faced with an error web page. Appending `&response_type=pin` to the page allows to get the PIN.

**Comment by jomo** [comment]
Is this is still the case with [v2.0.0](https://github.com/jomo/imgur-screenshot/pull/127)?

**Comment by oblitum** [comment]
Sorry my bad. The issue was with my terminal URL opener grabbing just half of the URL.
