### ISSUE TITLE
Config file? 

### ISSUE THREAD

**Issue by sabotarz** [jomo/imgur-screenshot#134]
/* In order to upload to your account, register a new application at:
https://api.imgur.com/oauth2/addclient
Select 'OAuth 2 authorization without a callback URL'
Then, set the imgur_acct_key (Client ID) and imgur_secret in your config. */

Everything's fine, but where is the config file?

**Comment by jomo** [comment]
See https://github.com/jomo/imgur-screenshot/wiki/Config
