### ISSUE TITLE
Uploaded pictures are smaler than my screenshot

### ISSUE THREAD

**Issue by artik** [jomo/imgur-screenshot#135]
Hi Jomo, and thanks for your script. I'm facing an issue: the uploaded pictures are smaller than on my disk. I created an ID and secret:

imgur_acct_key="7e4************"
imgur_secret="bf4837df901cda****************************"

upload process works, but then img is smaller than the original that is on my disk. Any help?

**Comment by jomo** [comment]
Do you mean dimensions or file size? Can you provide some specific details and/or an example image?

**Comment by artik** [comment]
Damn Jomo, I'm so sorry... My default imgur url chrome setting was set as 70%. I simply re-set it at 100%...

Sometimes you know....
