### ISSUE TITLE
Screenshot area border disappearing 

### ISSUE THREAD

**Issue by JPUnD** [jomo/imgur-screenshot#140]
Hi there, i've noticed a small bug, at least on my system, on this script.

**Description**
When calling imgur-screenshot i get my custom cursor as expected, and when i start to select the area to screenshot, the top and right corner (if i'm going left) and the left and top corner (if i'm going right) start vanishing and instead of being a rectangle i have this weird geometric shape.
That does not affect in any way the screenshot sent to imgur, it's only visual.

**Recording the bug**
This is an issue which is much easier to see than to explain, so here's a little video on what's going on:
[video](https://i.imgur.com/GDU3lZB.gif)
And here is the screenshot from that same video:
[screenshot](https://i.imgur.com/5rOm591.png)

**System**
i3-gaps 4.17
Manjaro
Kernel 4.19.66

Sorry i don't know how to post videos/images directly here :(
Thanks in advance!

**Comment by Brottweiler** [comment]
This is a bug with **scrot**. It's very old and have many bugs. I would suggest using something else, preferably [maim](https://github.com/naelstrof/maim).

**Comment by JPUnD** [comment]
ah, i had no idea, thanks for the suggestion, will use it instead of scrot. Will the script detect main once i removed scrot from my system or do i have to change something manually?

**Comment by Brottweiler** [comment]
The script tries to use scrot unless something else was specified in the config. Make a file `~/.config/imgur-screenshot/settings.conf` and paste

```bash
screenshot_select_command="maim -s %img"
screenshot_window_command="maim -u %img"
screenshot_full_command="maim %img"
```

**Comment by JPUnD** [comment]
Alright thanks, feel free to mark this as solved!

**Comment by Brottweiler** [comment]
You can just close it yourself. :)

**Comment by JPUnD** [comment]
Ah right, had no idea, although the button is right over there yeah xD
