### ISSUE TITLE
Run in background when Mac starts

### ISSUE THREAD

**Issue by AlecRust** [jomo/imgur-screenshot#142]
I'm looking to move away from the dead project [mac2imgur](https://github.com/mileswd/mac2imgur) and imgur-screenshot looks like it has great potential.

I think your README should read like the following though, to make it clear this is a CLI tool and not like mac2imgur that will start when your machine starts and be running in the background:

1. Run `imgur-screenshot.sh` in your terminal
2. Select an area of your screen
3. The screenshot is uploaded to Imgur

Are there any plans to add this feature, or ideas on how to automate this with an AppleScript for example if this is already supported?

**Comment by jomo** [comment]
I think the [usage section of the README](https://github.com/jomo/imgur-screenshot/tree/cleanup#usage) clearly states this.

This is a shell script, so how it's launched is out of scope, but I think it's possible to define keyboard shortcuts on MacOS to execute commands. Probably requires creating some plist entry somewhere, or third party software. Hope that helps.
