### ISSUE TITLE
upload failed

### ISSUE THREAD

**Issue by JouBqa** [jomo/imgur-screenshot#149]
What should I do?
`joni@pop-os:~$ imgur-screenshot
Please select area
Uploading '/home/joni/Pictures/imgur-2021_03_26-18:17:29.png'...
Upload failed: "{"data":{"id":"rT0ZuPf","title":"imgur-2021_03_26-18:17:29","description":null,"datetime":1616775455,"type":"image\/png","animated":false,"width":1152,"height":520,"size":496062,"views":0,"bandwidth":0,"vote":null,"favorite":false,"nsfw":null,"section":null,"account_url":null,"account_id":0,"is_ad":false,"in_most_viral":false,"has_sound":false,"tags":[],"ad_type":0,"ad_url":"","edited":"0","in_gallery":false,"deletehash":"aLgOUDjAjI6oPVQ","name":"","link":"https:\/\/i.imgur.com\/rT0ZuPf.png"},"success":true,"status":200}"

/home/joni/.local/bin/imgur-screenshot: line 285: jq: command not found
Failed to check for latest version: 
`

**Comment by jomo** [comment]
install jq. https://github.com/jomo/imgur-screenshot#dependencies
