### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by JouBqa** [jomo/imgur-screenshot#150]
I did a re-install of Pop_OS and now I can't upload it to imgur anymore

`joni@pop-os:~$ imgur-screenshot
Please select area
Uploading '/home/joni/Pictures/imgur-2021_05_04-09:46:31.png'...
Upload failed: "{"data":{"id":"YoTxZwu","title":"imgur-2021_05_04-09:46:31","description":null,"datetime":1620110803,"type":"image\/png","animated":false,"width":1794,"height":844,"size":157178,"views":0,"bandwidth":0,"vote":null,"favorite":false,"nsfw":null,"section":null,"account_url":null,"account_id":0,"is_ad":false,"in_most_viral":false,"has_sound":false,"tags":[],"ad_type":0,"ad_url":"","edited":"0","in_gallery":false,"deletehash":"BfcRDFuCbgNP4Ky","name":"","link":"https:\/\/i.imgur.com\/YoTxZwu.png"},"success":true,"status":200}"
/home/joni/.local/bin/imgur-screenshot: line 252: notify-send: command not found

/home/joni/.local/bin/imgur-screenshot: line 285: jq: command not found
Failed to check for latest version: 
`

**Comment by jomo** [comment]
https://github.com/jomo/imgur-screenshot#dependencies
