### ISSUE TITLE
Uploading multiple existing images

### ISSUE THREAD

**Issue by YogSottot** [jomo/imgur-screenshot#26]
I'm try to upload multiple existing images
```bash
imgur ~/Pictures/screenshots/*
```
But it only uploads the last of them.
Can you fix it, please?

Source code example https://github.com/carlcarl/imgurup
 https://github.com/kaimallea/node-imgur

**Comment by jomo** [comment]
Sorry for the delay, @YogSottot please try current master and let me know if it's alright.

**Comment by YogSottot** [comment]
Works good. Thank you.
