### ISSUE TITLE
Adding the name of the original file into the "Title"

### ISSUE THREAD

**Issue by YogSottot** [jomo/imgur-screenshot#27]
If I upload an existing file, the "Title" remains empty.  Is it possible to add an option to fill the title with the name of the original file?
The example https://imgur.com/2ygvL9S Title was added automatically by MyImgur tool.

**Comment by jomo** [comment]
This should be working now, please test the master branch and let me know.

**Comment by YogSottot** [comment]
Works good. Thank you.
