### ISSUE TITLE
Support the albums

### ISSUE THREAD

**Issue by YogSottot** [jomo/imgur-screenshot#28]
Is it possible to add a function to upload images to an existing album or create a new album?

**Comment by CestDiego** [comment]
@jomo when specifying an `album_title` in the preferences file, the script just creates a new album with the same title everytime it uploads an image. I think it'd be better for the workflow to suggest that one goes to the imgur album and copies it's id and replaces `album_title` with `album_id` in the preferences file

**Comment by jomo** [comment]
@CestDiego you can actually set the `album_id` in the config file. Is that what you're asking?
