### ISSUE TITLE
-u command bug

### ISSUE THREAD

**Issue by alexbooker** [jomo/imgur-screenshot#34]
When I enter the `-u` command:

```bash
imgur-screenshot.sh -u
```

I receive the following output:
```
Version v1.5.1 is available (You have v1.5.3)
Check https://github.com/jomo/imgur-screenshot/releases for more info.
```

Similarly, when I invoke the script:

```
imgur-screenshot.sh
```

I receive the following output:

```bash
booker@booker-MS-7681:/usr/local/bin$ imgur-screenshot.sh 
Please select area
Uploading '/home/booker/Pictures/imgur-2015_04_14-08:56:49.
...
Update found!
Version v1.5.1 is available (You have v1.5.3)
Check https://github.com/jomo/imgur-screenshot/releases for more info.
```

Obviously version 1.5.3 is more recent than version 1.5.1. 

I am running Ubuntu 14.10.

**Comment by jomo** [comment]
This will be fixed in a second :)

**Comment by alexbooker** [comment]
I guess you need to make a release on GitHub...?

Either way, thank you in advanced.

**Comment by jomo** [comment]
yes

**Comment by jomo** [comment]
There it is, it was a one-time bug because the version check was [changed] from comparing the `.version.txt` to using actual GitHub releases.

**Comment by alexbooker** [comment]
I updated my local script using `git clone` but the problem persists. 

```
Update found!
Version v1.5.4 is available (You have v1.5.3)
```

**Comment by jomo** [comment]
Then you don't have v1.5.4

**Comment by jomo** [comment]
Accidentally forgot a commit, should be fixed now

**Comment by alexbooker** [comment]
Works now yay :smile:.

By the way, is there an easier way to update? At the moment I do something like:

```bash
cd /usr/local/bin
sudo rm imgur-screenshot.sh
git clone https://github.com/jomo/imgur-screenshot
sudo cp imgur-screenshot/imgurscreenshot.sh imgurscreenshot.sh
sudo rm -rf imgur-screenshot
```

**Comment by jomo** [comment]
There is. Setup:

```bash
git clone https://github.com/jomo/imgur-screenshot
cd imgur-screenshot
sudo ln -s /path/to/imgur-screenshot.sh /usr/local/bin/imgurscreenshot
```

Now use `imgurscreenshot` from anywhere.

To update, simply use `git pull` in the imgur-screenshot directory

**Comment by alexbooker** [comment]
Wicked! Thanks!
