### ISSUE TITLE
Window Screenshot Mode

### ISSUE THREAD

**Issue by andreipoe** [jomo/imgur-screenshot#38]
I think it would be useful to have a parameter to take a screenshot of a full window by default instead of prompting to select an area. This could be either in the form of a configuration parameter or a command line argument. Is this something you would consider adding to the script?

**Comment by jomo** [comment]
You can change the `screenshot_select_command` in the config if you always take full shots.

I might add this as a CLI flag though.

**Comment by ftc2** [comment]
in os x, you can actually hit the space bar to toggle this behavior when you are in area-selection mode.

your mouse pointer will change from a reticle to a camera, and then you can just click on a window to select it.

**Comment by jomo** [comment]
Sorry for the long delay, you should now be able to do this using the `-w` or `--window` option.
