### ISSUE TITLE
Do i have to close the script after using it?

### ISSUE THREAD

**Issue by Gameboy24** [jomo/imgur-screenshot#39]
So when I use this script on the terminal on linux, it works but i have to ctrl+c to end it after it is done. Does that mean if I bind it to a shortcut it will have multiple instances open for every time i take a screenshot? Thanks, and sorry if the questions out of place, I just don't know where to put it.

**Comment by jomo** [comment]
This shouldn't happen. Can you paste your terminal output?

**Comment by Gameboy24** [comment]
Here's the terminal output.

```
Please select area
Uploading '/home/ajeet/Pictures/imgur-2015_06_14-15:40:31.png'...

image  link: https://i.imgur.com/3ZVhFCN.png
delete link: https://imgur.com/delete/Cc2AeXpYLDMf7HD
URL copied to clipboard
imgur-screenshot.sh: line 334: /home/ajeet/.imgur-screenshot.log: Permission denied
Opening 'xdg-open https://i.imgur.com/3ZVhFCN.png'

Using PPAPI flash.
Version v1.5.4 is up to date.
ajeet@ajeet-desktop:~/Downloads/archives/imgur-screenshot-master$ Fontconfig warning: "/etc/fonts/infinality/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/infinality/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
Created new window in existing browser session.
```

**Comment by jomo** [comment]
I assume this is due to `xdg-open` blocking until your browser is closed.
Can you try setting `open_command="xdg-open %url &"` in your config file or running with `--open=false` and see if this still happens.

If that fixes it, I'll append `&` to the xdg-open command per default in the next release.

**Comment by jomo** [comment]
@Gameboy24 have you tried the suggestion in my latest comment?

**Comment by vitorgalvao** [comment]
@jomo I’d say five months with no reply is enough to close the issue. This is either no longer an issue, or the user moved on.
