### ISSUE TITLE
Add a flag for full screenshot

### ISSUE THREAD

**Issue by fbm-static** [jomo/imgur-screenshot#40]
Hello,

Right now, when launching the application a selection of a portion of the screen is needed. I press <kbd>esc</kbd> to have it not upload, so there is now way at the moment to fire up `screenshot_window_command` with `exit_on_selection_fail` set to `true`.

I think it would be nice to have, maybe, an `-f` flag to trigger the `screenshot_window_command` instead of `screenshot_select_command` to work with `exit_on_selection_fail`.

Thanks.

**Comment by jomo** [comment]
as with #38, I'll add this in the next release.

**Comment by fbm-static** [comment]
Hehe, Thanks!! May I know what screen selection application you used? It doesn't seem to be scrot.

**Comment by jomo** [comment]
It defaults to `screencapure` on OS X and `scrot` everywhere else, [see here](https://github.com/jomo/imgur-screenshot/blob/9bbe72dded2444e225b757f6a249ba153c8caf5e/imgur-screenshot.sh#L30-L38).

**Comment by krompus** [comment]
Awesome! I just downloaded this program, and it works a treat. The only thing it's missing IMO is the flag for fullscreen -- I'm going to bind fullscreen to PrtScr, and selection to Shift+PrtScr.

Thanks, jomo!

**Comment by jomo** [comment]
Sorry for the long delay, you should now be able to do this using the `-f` or `--full` option.
