### ISSUE TITLE
increasing upload_connection_timeout values

### ISSUE THREAD

**Issue by bookletchoir** [jomo/imgur-screenshot#43]
tl;dr: line 40, ```upload_connection_timeout='5'``` isn't enough for large image file or slow connection, so i suggest to increase it to 10 (or larger) or remove it from the parsing options for cURL.

Old issue: https://github.com/jomo/imgur-screenshot/issues/42

When using new file from master branch, the curl(3) error is no more, but it's still failed to upload
```shell
$ ./imgur-screenshot.sh 
Please select area
Uploading '/home/yumeko/Pictures/Screenshots/imgur-2015_07_22-23:21:27.png'...
Upload failed: "curl: (28) Resolving timed out after 5513 milliseconds"

Version v1.5.4 is up to date.
```

From the --debug option, i see the connection time isn't enough for large image files
```shell
$ curl --compressed --connect-timeout 5 -m 120 -fsSL --stderr - -H 'Authorization: Client-ID 9e603f08c0e541c' -F title=imgur-2015_07_22-23:13:42 -F image=@/home/yumeko/Pictures/Screenshots/imgur-2015_07_22-23:13:42.png https://api.imgur.com/3/image                                       
curl: (28) Resolving timed out after 5515 milliseconds
```

So i tries to increase it to 10, or remove it from the parsing options
```shell
$ curl --compressed -m 120 --retry 1 -fsSL --stderr - -H 'Authorization: Client-ID 9e603f08c0e541c' -F title=imgur-2015_07_22-23:13:42 -F image=@/home/yumeko/Pictures/Screenshots/imgur-2015_07_22-23:13:42.png https://api.imgur.com/3/image                     
{"data":{"id":"dOXCu2z","title":"imgur-2015_07_22-23:13:42","description":null,"datetime":1437581795,"type":"image\/png","animated":false,"width":662,"height":557,"size":325847,"views":0,"bandwidth":0,"vote":null,"favorite":false,"nsfw":null,"section":null,"account_url":null,"account_id":0,"comment_preview":null,"deletehash":"LYgnZm2H8aBTDSM","name":"","link":"http:\/\/i.imgur.com\/dOXCu2z.png"},"success":true,"status":200}%
```

And well, the result's there.

**Comment by jomo** [comment]
`--connect-timeout`
> Maximum  time in seconds that you allow the connection to the server to take. **This only limits the connection phase**, once curl has connected this option is of no more use.

5 seconds should be enough to *establish* a connection.
The actual time to upload the image is `-m 120` (2 minutes). This should be fine as well.

> `curl: (28) Resolving timed out after 5515 milliseconds`

This does look like a DNS issue though. Can you reach https://api.imgur.com?

-----

However, you can tweak these `upload_connect_timeout`, `upload_timeout`, `upload_retries` settings in [your config](https://github.com/jomo/imgur-screenshot/wiki/Config) if you're on a slow network.

**Comment by bookletchoir** [comment]
My mistake for the values names.

But in my case, i removed all ```upload_connect_timeout```, ```upload_timeout``` and ```upload_retries``` from the cURL options and it works just fine.

Maybe I'll have a look with my DNS and see again.

**Comment by jomo** [comment]
Okay, this seems to be a problem with your (apparently rather slow) internet connection.
Glad you could fix it.

Can you open a new issue for your 2nd Edit?
