### ISSUE TITLE
upload an entire directory of images as an album

### ISSUE THREAD

**Issue by ftc2** [jomo/imgur-screenshot#44]
it would be cool to be able to:
```shell
imgur-screenshot.sh --album some_album_name /path/to/some/dir/of/images
```
and have it upload all of the images in there to an album.

here is some stuff that might be helpful:

https://help.imgur.com/hc/en-us/articles/201424906-What-file-types-are-allowed-
>What file types are allowed?
>Sarah Schaaf - March 16, 2015 16:08
>
>JPEG, PNG, GIF, APNG, TIFF, BMP, PDF, XCF (GIMP). Please note that TIFF, BMP, PDF and XCF (GIMP) will be converted to PNG on upload. PNGs over 756KB are automatically converted to JPG. 

some code that should work for that:
```shell
ls | egrep -i '\.jpg$|\.jpeg$|\.jpe$|\.jif$|\.jfif$|\.jfi$|\.png$|\.gif$|\.apng$|\.tiff$|\.tif$|\.bmp$|\.pdf$|\.xcf$'
```
^ that should search for all allowed image files (and is case-insensitive for those extensions because of the -i flag)

what do you think? do you like the idea?

**Comment by jomo** [comment]
What you can do is
```shell
imgur-screenshot -a "my album" /path/to/some/dir/of/images/*
```
Which will upload all files in that directory, or you could use
```shell
imgur-screenshot -a "my album" /path/to/some/dir/of/images/*.{jpg,jpeg,png,gif,…}
```
or
```shell
for image in ls | egrep -i '\.jpg$|\.jpeg$|\.jpe$|\…'; do
  imgur-screenshot -A "$some_album_id" "$image"
done
```

However, I don't think it would be used a lot, so I'll close this. Feel free to fork and add this, though!
