### ISSUE TITLE
Notification and mouse cursor on select area

### ISSUE THREAD

**Issue by bookletchoir** [jomo/imgur-screenshot#45]
First, it'd be nice to have a notification by ```notify-send``` when the script start
```
notify-send -i "/path/to/imgur/icon.png" "Imgur Screenshot" "Please select area"
```

Second, when selecting area, please change cursor to "select mode" (something like plus sign), because
- If you start to drag cursor from an empty zone, it works fine.
- If you start to drag cursor from a text field, like terminal, text editor zone, ..., it'll select texts from the text field, not capture area mode from the script.

So, making the cursor change to "select mode" to ignore all of the other program's mouse action until you're done with selecting area to take screenshot, it'd be nice.

**Comment by jomo** [comment]
I could definitely do the notification.

The selection cursor however is part of the screen shot tool (defaulting to `scrot` / `screencapture`). So you will have to change the tool. Ignoring other program's mouse actions is also the screen shot tool's job.

**Comment by bookletchoir** [comment]
If that's the case, so i'll replace ```scrot``` with ```maim``` in ```~/.config/imgur-screenshot/settings.conf```.

Thanks anyway.
