### ISSUE TITLE
Seems that api has changed

### ISSUE THREAD

**Issue by CestDiego** [jomo/imgur-screenshot#46]
I get this now

```
Error: Couldn't get access token from 'https://api.imgur.com/oauth2/token'
```

And the webpage says that some required fields were missing

**Comment by jomo** [comment]
It's working for me. Maybe the API was down. Is this still an issue?
If it's still broken, can you pull from master and provide the output, please?

**Comment by CestDiego** [comment]
I get 
`Upload failed: "curl: (22) The requested URL returned error: 400 Bad Request"`

**Comment by CestDiego** [comment]
oh...I deleted the credentials file. And it works now. maybe it was expired I don't know D:

**Comment by jomo** [comment]
Yep, that happens when you make calls to imgur's API with invalid parameters.
I will leave this open and consider adding some extra checks, though.
