### ISSUE TITLE
re-uploading images to imgur

### ISSUE THREAD

**Issue by ftc2** [jomo/imgur-screenshot#47]
do you know if the imgur api allows for re-uploading images to imgur (e.g. urls of images hosted elsewhere)?

you can do this from the imgur website.  can be useful for re-hosting images hosted on 'bad' image hosts.

https://i.imgur.com/4a1vdX5.png

if it's possible, it would be a cool feature addition.
possibly used like:
`imgur-screenshot.sh [options] URLtoReuploadToImgur`

i suppose the image could be temporarily downloaded to a temp dir and then uploaded, but when you use the feature on imgur's website, i assume imgur's servers do the downloading for you

**Comment by jomo** [comment]
Yes, [the API](http://api.imgur.com/endpoints/image#image-upload) does allow this:
```
type | optional | The type of the file that's being sent; file, base64 or URL
```

You can also do this using one line of CLI:
```shell
wget "http://oi45.tinypic.com/296gdb7.jpg" -O imgur.png && imgur-screenshot.sh imgur.png
```

However, I think it's not really worth implementing as too few people would probably use it.
Unless I hear otherwise, I'll keep this closed. Feel free to fork!

**Comment by ftc2** [comment]
i added it, check it out
https://github.com/jomo/imgur-screenshot/pull/48
