### ISSUE TITLE
Missing config

### ISSUE THREAD

**Issue by lspan** [jomo/imgur-screenshot#49]
Is there anywhere else the settings.conf could be? I'm trying to put in my client id and secret but I've been searching around my file system for about an hour now with no results. I can upload screenshots anonymously so it must be there. I don't even have an imgur-screenshot directory under my .config. I'm running crouton on a chromebook with ubuntu 12.04. Sorry I had to bug you over this, but my Googlefu wasn't strong enough.

**Comment by jomo** [comment]
The [default config](https://github.com/jomo/imgur-screenshot/blob/84b2f4a7af9a9137c9acad2bb9b576be6953ed5c/imgur-screenshot.sh#L26-L76) is part of the script itself with the client id [defined in this line](https://github.com/jomo/imgur-screenshot/blob/84b2f4a7af9a9137c9acad2bb9b576be6953ed5c/imgur-screenshot.sh#L30).

Configuration and credentials *can* be overridden in `~/.config/imgur-screenshot/settings.conf` and `~/.config/imgur-screenshot/credentials.conf`, but if they don't exist (or don't overwrite anything) the default applies.
