### ISSUE TITLE
--auto-delete should be --auto_delete

### ISSUE THREAD

**Issue by vitorgalvao** [jomo/imgur-screenshot#53]
`_` instead of `-`, to be consistent with the other options. I’d submit a PR now, but that would conflict with https://github.com/jomo/imgur-screenshot/pull/52, which needs to be handled first.

I’d also like to run other consistency improvements in help (capitalisation is inconsistent) and in the script as a whole ( `$var` and `${var}` are used interchangeably without good logic), but those are all dependent on the aforementioned PR.

**Comment by jomo** [comment]
Fixed the other way in 0fe3bdff43a66e8e0547c903d25142019984c2ac, thanks!

**Comment by vitorgalvao** [comment]
Great! Thank you.
