### ISSUE TITLE
Request: option to resample dpi for retina screens

### ISSUE THREAD

**Issue by vitorgalvao** [jomo/imgur-screenshot#55]
In retina screens, although we see the screenshots we take at the same size we see what the took a screenshot from, when sending it to imgur, what we’ll get back is an image much larger (in width/height terms). This is due to the dpi of the images themselves. [Link to a post explaining it further](http://benalman.com/news/2012/07/fixing-retina-image-scaling/).

Although sometimes desirable, it is conversely sometimes undesirable as well, so it’d be good to have an option to resample the image before uploading. Most of the work can already be found [in the form of a script](https://github.com/cowboy/dotfiles/blob/master/bin/resample-dpi).

**Comment by jomo** [comment]
Check out the wiki page about the [config](https://github.com/jomo/imgur-screenshot/wiki/Config).
This could be done with something like:
```bash
edit_command="~/bin/resample-dpi %img"
```

Then use `imgur-screenshot.sh -e true` or configure `edit="true"` to make this the default.

**Comment by vitorgalvao** [comment]
`edit_command` can’t be set via a flag at run time, though. Why not?

**Comment by jomo** [comment]
Initially it was meant to just open the image in the image editor of your choice before uploading. Usually you wouldn't change it very often. I'll be happy to merge a PR.

**Comment by vitorgalvao** [comment]
Added option for `edit_command` on runtime on https://github.com/jomo/imgur-screenshot/pull/60.
