### ISSUE TITLE
Decide function definition style

### ISSUE THREAD

**Issue by vitorgalvao** [jomo/imgur-screenshot#59]
Currently, function definitions follow the form `function function_name() {…`. That doesn’t make sense in bash, where we don’t put anything between the `()`. It should either be `function function_name {…` or `function_name() {…`, never both.

The final pick is a stylistic choice, so rather than submit a PR, a issue is more appropriate.

**Comment by laur89** [comment]
It's really a matter of style really. As long as everyone sticks to one certain style, I'm ok.

**Comment by vitorgalvao** [comment]
Closed in favour of https://github.com/jomo/imgur-screenshot/pull/104.
