### ISSUE TITLE
Open is set to false but its still opening in browser

### ISSUE THREAD

**Issue by nahtnam** [jomo/imgur-screenshot#65]
Hey!

I have this set in the config:
```
...
file_dir="$HOME/Pictures/screenshots"
upload_connect_timeout="5"
upload_timeout="120"
upload_retries="1"
screenshot_select_command="scrot -s %img" # OS X: "screencapture -i
%img"
screenshot_window_command="scrot %img" # OS X: "screencapture -iWa %img"
edit_command="gimp %img"
edit="false"
exit_on_selection_fail="true"
edit_on_selection_fail="false"
exit_on_album_creation_fail="true"
open="false" // OPEN IS SET TO FALSE
log_file="$HOME/.imgur-screenshot.log"
copy_url="true"
keep_file="true"
check_update="true"
```

but when I take a screenshot, it still opens in Google Chrome.

Thanks.

**Comment by jomo** [comment]
Can you try with `--debug` as the first argument and paste the output here?

**Comment by nahtnam** [comment]
Here you go:

**Comment by jomo** [comment]
Looks like you got a syntax error in your config file:

> end with '.png!'

/home/nahtnam/.config/imgur-screenshot/settings.conf: line 10: end: command not found
/home/nahtnam/.config/imgur-screenshot/settings.conf: line 27: unexpected EOF while looking for matching `"'
/home/nahtnam/.config/imgur-screenshot/settings.conf: line 28: syntax error: unexpected end of file

**Comment by nahtnam** [comment]
Ah yes.

Thanks a lot!
