### ISSUE TITLE
imgur-screenshot.sh --check doesn't work on Linux

### ISSUE THREAD

**Issue by qolop** [jomo/imgur-screenshot#66]
I'm running Ubuntu 15.10. Performing the command "imgur-screenshot.sh --check" in the directory where imgur-screenshot is installed does not do anything (I get "command not found"). To clarify, I did see the .README and was able to install the dependencies like I normally would.

**Comment by jomo** [comment]
Please paste output of `imgur-screenshot.sh --debug --check`.

**Comment by qolop** [comment]
```
patrick@patrick:~/imgur-screenshot$ imgur-screenshot.sh --debug --check
imgur-screenshot.sh: command not found
```

**Comment by jomo** [comment]
Hmm quite obviously `imgur-screenshot.sh` is not there. How did you install it and which version of the script do you have? Can you paste output of `ls -lah` in the install directory?

**Comment by qolop** [comment]
No, imgur-screenshot.sh is there. I am able to take screenshots using this too.

**Comment by qolop** [comment]
Nevermind, a noob mistake on my part I guess. If I put a ./ before the command, everything works fine.
