### ISSUE TITLE
403 Permission Denied

### ISSUE THREAD

**Issue by qolop** [jomo/imgur-screenshot#67]
I'm getting this error whenever I take a screenshot with the program. I have all the dependencies installed. I haven't used this program for over a month, but I know back in February this did work for me. I'm running Ubuntu 15.10 64-bit. This error pops up in the Ubuntu notification.:
```
Imgur: Upload failed :(
curl: (22) The requested URL returned error: 403 Permission Denied
```
I have also not modified the program in any way (e.g. adding my own imgur account IDs from API).

**Comment by jomo** [comment]
I just noticed this as well. Looks like imgur changed something on their API, I'm looking into it.

**Comment by qolop** [comment]
Thanks for the quick reply. :)

**Comment by jomo** [comment]
Looks like imgur revoked the client ID:
```JSON
{
  "data": {
    "error": "Invalid client_id",
    "request": "/3/image",
    "method": "POST"
  },
  "success": false,
  "status": 403
}
```

I'll have to talk to imgur about this.

**Comment by jomo** [comment]
Apparently they also removed https://api.imgur.com/whitelist ([archive link](http://web.archive.org/web/20140626000307/http://api.imgur.com/whitelist)) which could be used to request a rate limiting exception.


Here's the email they sent me after I filled out that form a year ago:
```
Subject: Imgur API Whitelist
Date:    Mon, 23 Mar 2015 18:02:00 +0000
From:    Imgur API <api@imgur.com>
To:      jomo


Congratulations! Your awesome app, imgur-screenshot, with client-id, 9e603f08c0e541c, has been approved for our whitelist!

Your application will have all the access it needs, however, we will still rate-limit by IP to prevent any one user from spamming the application.

Enjoy! <3 @imgurAPI
```

**Comment by jomo** [comment]
Apparently the issue was my own fault. I tried cleaning up some of my imgur apps and accidentally deleted the public Client ID for this app. I'm so sorry everyone!

I've asked imgur to re-activate the old Client ID if possible.

-----

**I have released a new version with a new Client ID**, please run `imgur-screenshot.sh -u` for the update.

Please note the new Client ID is not whitelisted for rate limit exceptions, so you may run into that limit.

Alternatively, instead of updating you can add the following line to
`~/.config/imgur-screenshot/settings.conf`:
```
imgur_anon_id="ea6c0ef2987808e"
```

-----

I'll leave this issue open for a while for people to notice it. Thanks for reporting!

**Comment by p0rsche** [comment]
Latest update fixes the issue. Thanks.

**Comment by jomo** [comment]
> I've asked imgur to re-activate the old Client ID if possible.

Got a response from Imgur guy @kecramer, he's looking into it 👍

**Comment by clathrop** [comment]
@jomo thanks for the update, anyway we can get the brew version updated to 1.7.1 so I can pull it down without having to get my hands dirty? Appreciate it ;)

**Comment by jomo** [comment]
@clathrop I submitted a PR to homebrew: https://github.com/Homebrew/homebrew-core/pull/138.
Looks like @ValdikSS has also updated the AUR package 👍

**Comment by clathrop** [comment]
@jomo awesome, thx! Great tool you got here, I was about to make my own but luckily came across this project. 😄 Ever consider integrating with google drive to add a bit more security to the uploads? May come in handy for sharing screenshots at the enterprise level.

**Comment by jomo** [comment]
Homebrew has been [updated](https://github.com/Homebrew/homebrew-core/pull/138#issuecomment-207109882), please run `brew update && brew upgrade imgur-screenshot`.

I don't plan to add google drive support, that'd be a whole different thing. However you can upload to your imgur account.

**Comment by Brottweiler** [comment]
I started getting this error today. For what it's worth, I recently updated to 1.7.2 and 1.7.3. Today is the first time I encountered the issue.

**Comment by jomo** [comment]
Having no issues here, can you run with `--debug` as the first arg and attach the output?

**Comment by Brottweiler** [comment]
@jomo How much of the debug info is sensitive? Should I share all of it? Isn't the access token sensitive?

**Comment by jomo** [comment]
Strip out `imgur_acct_key`, `imgur_secret`, `access_token`, `refresh_token` (and possibly the delete hash/link in case you get one).

**Comment by Brottweiler** [comment]
@jomo https://gist.github.com/ddc4b95b2844896c2dc8df55bf0ea5a6
The secret/refresh and access token were in several places so had to remake it a few times, but this should be fine.

**Comment by jomo** [comment]
Moved to #72 since it affects account uploads only.

**Comment by jomo** [comment]
Closing this as no more issues with anonymous uploads have been reported.
