### ISSUE TITLE
"curl: (6) name lookup timed out"

### ISSUE THREAD

**Issue by AyushBhat** [jomo/imgur-screenshot#68]
each time i run the script i get that error "curl: (6) name lookup timed out"

**Comment by jomo** [comment]
Sounds like an issue with your DNS. If you think it's not, please post output with `--debug`.

**Comment by AyushBhat** [comment]
`bash-4.2$ imgur-screenshot.sh --debug
########################################
Enabling debug mode
Please remove credentials before pasting
########################################

Linux ayush 4.4.6 #1 SMP Tue Apr 5 16:50:38 IST 2016 x86_64 Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz GenuineIntel GNU/Linux
'/usr/bin/imgur-screenshot.sh' '--debug' 

+ current_version=v1.7.1
+ imgur_anon_id=ea6c0ef2987808e
+ imgur_icon_path=/home/ayush/Pictures/imgur.png
+ imgur_acct_key=
+ imgur_secret=
+ login=false
+ album_title=
+ album_id=
+ credentials_file=/home/ayush/.config/imgur-screenshot/credentials.conf
+ file_name_format=imgur-%Y_%m_%d-%H:%M:%S.png
+ file_dir=/home/ayush/Pictures
+ upload_connect_timeout=5
+ upload_timeout=120
+ upload_retries=1
+ is_mac
+ uname
+ grep -q Darwin
+ screenshot_select_command='scrot -s %img'
+ screenshot_window_command='scrot %img'
+ screenshot_full_command='scrot %img'
+ open_command='xdg-open %url'
+ open=true
+ mode=select
+ edit_command='gimp %img'
+ edit=false
+ exit_on_album_creation_fail=true
+ log_file=/home/ayush/.imgur-screenshot.log
+ auto_delete=
+ copy_url=true
+ keep_file=true
+ check_update=true
+ settings_path=/home/ayush/.config/imgur-screenshot/settings.conf
+ '[' -f /home/ayush/.config/imgur-screenshot/settings.conf ']'
+ '[' '' = --check ']'
+ '[' 0 '!=' 0 ']'
+ '[' false = true ']'
+ '[' -n '' ']'
+ '[' -z '' ']'
+ upload_files[0]=
+ for upload_file in '"${upload_files[@]}"'
+ '[' -z '' ']'
+ cd /home/ayush/Pictures
++ date +imgur-%Y_%m_%d-%H:%M:%S.png
+ img_file=imgur-2016_04_06-21:00:37.png
+ take_screenshot imgur-2016_04_06-21:00:37.png
+ echo 'Please select area'
Please select area
+ is_mac
+ uname
+ grep -q Darwin
+ sleep 0.1
+ cmd=screenshot_select_command
+ cmd='scrot -s imgur-2016_04_06-21:00:37.png'
++ scrot -s imgur-2016_04_06-21:00:37.png
+ shot_err=
+ '[' 0 '!=' 0 ']'
+++ dirname imgur-2016_04_06-21:00:37.png
++ cd .
+++ pwd
+++ basename imgur-2016_04_06-21:00:37.png
++ echo /home/ayush/Pictures/imgur-2016_04_06-21:00:37.png
+ img_file=/home/ayush/Pictures/imgur-2016_04_06-21:00:37.png
+ '[' '!' -f /home/ayush/Pictures/imgur-2016_04_06-21:00:37.png ']'
+ '[' false = true ']'
+ '[' false = true ']'
+ upload_anonymous_image /home/ayush/Pictures/imgur-2016_04_06-21:00:37.png
+ echo 'Uploading '\''/home/ayush/Pictures/imgur-2016_04_06-21:00:37.png'\''...'
Uploading '/home/ayush/Pictures/imgur-2016_04_06-21:00:37.png'...
++ echo /home/ayush/Pictures/imgur-2016_04_06-21:00:37.png
++ rev
++ cut -d / -f 1
++ cut -d . -f 2-
++ rev
+ title=imgur-2016_04_06-21:00:37
+ '[' -n '' ']'
++ curl --compressed --connect-timeout 5 -m 120 --retry 1 -fsSL --stderr - -H 'Authorization: Client-ID ea6c0ef2987808e' -F title=imgur-2016_04_06-21:00:37 -F 'image=@"/home/ayush/Pictures/imgur-2016_04_06-21:00:37.png"' https://api.imgur.com/3/image
+ response='curl: (6) name lookup timed out'
+ egrep -q '"success":\s*true'
++ egrep -o '"error":\s*"[^"]+"'
++ cut -d '"' -f 4
+ err_msg=
+ test -z ''
+ err_msg='curl: (6) name lookup timed out'
+ handle_upload_error 'curl: (6) name lookup timed out' /home/ayush/Pictures/imgur-2016_04_06-21:00:37.png
+ error='Upload failed: "curl: (6) name lookup timed out"'
+ echo 'Upload failed: "curl: (6) name lookup timed out"'
Upload failed: "curl: (6) name lookup timed out"
+ echo -e 'Error\t/home/ayush/Pictures/imgur-2016_04_06-21:00:37.png\tUpload failed: "curl: (6) name lookup timed out"'
+ notify error 'Upload failed :(' 'curl: (6) name lookup timed out'
+ is_mac
+ uname
+ grep -q Darwin
+ '[' error = error ']'
+ notify-send -a ImgurScreenshot -u critical -c im.error -i /home/ayush/Pictures/imgur.png -t 500 'imgur: Upload failed :(' 'curl: (6) name lookup timed out'
+ '[' true = false ']'
+ echo ''

+ '[' true = true ']'
+ check_for_update
++ curl --compressed -fsSL --stderr - https://api.github.com/repos/jomo/imgur-screenshot/releases
++ egrep -m 1 --color 'tag_name":\s*".*"'
++ cut -d '"' -f 4
+ remote_version=v1.7.1
+ '[' 0 -eq 0 ']'
+ '[' '!' v1.7.1 = v1.7.1 ']'
+ '[' -z v1.7.1 ']'
+ '[' -z v1.7.1 ']'
+ echo 'Version v1.7.1 is up to date.'
Version v1.7.1 is up to date.
`

**Comment by AyushBhat** [comment]
thats what it says

**Comment by jomo** [comment]
Yep, that's a DNS issue. It's either damn slow or can't be reached. Check if https://api.imgur.com/ in your browser works.

**Comment by AyushBhat** [comment]
yes https://api.imgur.com/ works, how could i possibly fix it?

**Comment by jomo** [comment]
You might want to use a proper DNS server. If you've tested with Google Chrome, it probably uses Google's DNS servers. Use that (or anything else that's reasonably good for you) as system DNS.

**Comment by AyushBhat** [comment]
okay, thanks
