### ISSUE TITLE
Endless upload loop under kde

### ISSUE THREAD

**Issue by vityas-off** [jomo/imgur-screenshot#69]
When using kde after taking a screenshot starts endless loop of uploading this screenshot to imgur. When not using kde everything works fine.
Linux w 4.5.0-1-ARCH, plasmashell 5.6.2
[debug2.txt](https://github.com/jomo/imgur-screenshot/files/224392/debug2.txt)
[syslog.txt](https://github.com/jomo/imgur-screenshot/files/224401/syslog.txt)

**Comment by jomo** [comment]
The log you provided only uploaded [one image](https://i.imgur.com/NsDqgnp.png) and exits afterwards. Possibly an issue with your setup or kde?

**Comment by vityas-off** [comment]
In systemlog there is much more than one uploaded image.
i deleted .config/{kde*,plasma*} and reinstalled imgur-screenshot.
Still occurs https://my.mixtape.moe/ibevkj.webm
[uploads.txt](https://github.com/jomo/imgur-screenshot/files/233740/uploads.txt)

**Comment by vityas-off** [comment]
I fixed issue commenting string 56
`#  open_command="xdg-open %url"
Now script  forks fine.

**Comment by jomo** [comment]
```
Apr 25 02:37:46 w kioexec[7137]: command= "imgur-screenshot %F" args= ("imgur-screenshot %F", "https://i.imgur.com/HNGslWN.png")
Apr 25 02:37:46 w kioexec[7137]: Copying QUrl("https://i.imgur.com/HNGslWN.png")  to QUrl("file:///home/w/.cache/kioexec/krun/7137_0_HNGslWN.png")
Apr 25 02:37:46 w kioexec[7137]: EXEC  "/usr/bin/imgur-screenshot /home/w/.cache/kioexec/krun/7137_0_HNGslWN.png"
```
Looks like it downloads the (just uploaded file) to `/home/w/.cache/kioexec/krun/` (using [kioexec](http://manpages.org/kioexec)) and then runs `imgur-screenshot` with that file passed as an argument.

**Comment by vityas-off** [comment]
Yes, seems this is how it is. Changing "Open http/https URLS" from "in an application based on the contents of the URL" to "firefox" in kde-system-settings resolvs issue without editing script and uploaded image opens in browser after upload.
