### ISSUE TITLE
"Version v1.7.2 is available" while I already have the newest version

### ISSUE THREAD

**Issue by milandamen** [jomo/imgur-screenshot#71]
I have the newest version (`git pull` and comparing `git log` to the commits on GitHub), I think you forgot to update the version number in imgur-screenshot.sh on line 20.

**Comment by jomo** [comment]
Missed that, should be fixed with [release v1.7.3](https://github.com/jomo/imgur-screenshot/releases/tag/v1.7.3). Thanks for reporting!
