### ISSUE TITLE
403 Permission Denied (uploading to account)

### ISSUE THREAD

**Issue by jomo** [jomo/imgur-screenshot#72]
Me and @Brottweiler [got that error](https://github.com/jomo/imgur-screenshot/issues/67#issuecomment-214314220) when trying to upload to an account today, it was definitely working a few days ago. Now the 403 response says the token is invalid.

Current workaround:
- delete the `credentials.conf`
- remove `imgur_acct_key` and `imgur_secret` from `settings.conf`
- follow the instructions when running `imgur-screenshot -c`

The only change to handling authorized uploads was commit dc8eaa6638c357a4fa5e2ee2960726ee4c92e942, I don't think that should have made anything worse.

Let's see if this happens again with new generated auth keys.

**Comment by nahtnam** [comment]
Following the instructions fixed it. Can you add it to the README for more visibility until its fixed?

Thanks.

**Comment by Brottweiler** [comment]
This workaround fixed it for limited time, today right now I am getting the same error again.

**Comment by jomo** [comment]
Can confirm. I'm not sure why this happens. Will have to read the API docs again but I feel like it's imgur causing it.

**Comment by Brottweiler** [comment]
Btw, you only need to go to https://imgur.com/account/settings/apps and press "generate new secret" and  copy paste the secret to your `settings.conf`, then you need to run it once to get the PIN and enter that. You don't need to register new application.

**Comment by ValdikSS** [comment]
Breaks for me every day.

**Comment by tagplus5** [comment]
Looks like it is a problem with token expire time. My solution is add to cron
`0 0 * * * imgur-screenshot -c > dev/null`

**Comment by jomo** [comment]
The bug has actually been there since the feature was introduced in b71655eb03220382379d2d0c6490fc61dd0910b1, but another bug #70 caused it to have no impact because it would refresh the token every time the script ran.

**Comment by jomo** [comment]
Fix released in [v1.7.4](https://github.com/jomo/imgur-screenshot/releases/tag/v1.7.4).
Homebrew: https://github.com/Homebrew/homebrew-core/pull/874

**Comment by jomo** [comment]
Looking at it again, the commit doesn't fix it. In bash, a return value of 0 means true / success, anything greater is false / error:
```bash
[ 1 -gt 0 ]
# return value: 0
```
However, bash's arithmetic evaluation returns the result of the computation. In cases of a binary result, it returns it as 0 or 1. Thus 0 means false and 1 means true:
```bash
$((1 > 0))
# return string: 1
```

I.e. the expiry check was correct. I have reverted to 1.7.3 locally and double checked token expiry detection works as intended.

But I'm also able to upload to my account. Is this still an issue for others as of today?

**Comment by Brottweiler** [comment]
@jomo I think I've reset my token 3 times total, but that 3rd time was maybe two-three days ago, and it's still working even before your fix today. So, right now it's working, and I'll update this if it stops working again.

**Comment by ValdikSS** [comment]
v1.7.4 works fine for me while v1.7.3 losts authentication every day.

**Comment by Brottweiler** [comment]
Yeah, it has worked for me quite a while now.

**Comment by jomo** [comment]
@ValdikSS did you use v1.7.3 **recently**? I'm asking because I believe the issue was a temporary problem at imgur and not related to the code. I'm using v1.7.3 locally and it correctly requested a new token after (and only after) it expired. I'm able to upload to my account without any issues.

As explained in my previous comment, v1.7.4 shouldn't handle token expiration correctly.

**Comment by ValdikSS** [comment]
@jomo, yes, I switched to 1.7.4 3 days ago after 4 days of 1.7.3 which made me repeat steps to fix it every day.

**Comment by jomo** [comment]
Interesting, I've used v1.7.3 for about a month. The token actually expired today and I didn't have any issues so far.

**Comment by khurshid-alam** [comment]
@jomo I can reproduce the issue with 1.7.4. After resetting everything next day it's the same issue. Please fix it.

**Comment by khurshid-alam** [comment]
@jomo  Now I am using 1.7.3 and I can still reproduce this.

**Comment by Brottweiler** [comment]
I've not had any problems in a long time now.

**Comment by khurshid-alam** [comment]
It is happening wih me for both 1.7.3 and 1.7.4. It works if I reset authentication. But every-time after the token expire, it seems it can not get new token and hence getting permission denied.

**Comment by jomo** [comment]
Sorry, I can't reproduce either. v1.7.3 should be working, see [here](https://imgur.com/a/yS4My).
Please try deleting your credentials.conf and remove `imgur_acct_key` + `imgur_secret` from settings.conf. Run `imgur-screenshot -c`, then follow the instructions and try again.

**Comment by khurshid-alam** [comment]
@jomo Any specific reason for removing imgur_acct_key + imgur_secret from settings.conf? Because I still want to use my own acc_key.

Update: Ok. After removing everything and reconnecting it is working for now. Hope it will still work tomorrow. Thanks.

**Comment by kfpo** [comment]
@jomo 
> Please try deleting your credentials.conf and remove imgur_acct_key + imgur_secret from settings.conf. Run imgur-screenshot -c, then follow the instructions and try again.
After reconnect this error strikes again after few days.

**Comment by JPUnD** [comment]
I wanna point out that i had this same issue today, the workaround fixed it, lets see if sticks (was using it for a few weeks at most)
