### ISSUE TITLE
Part of screenshot selection outlines show in image

### ISSUE THREAD

**Issue by qolop** [jomo/imgur-screenshot#75]
Here's an example:

![](https://i.imgur.com/K0nZQeV.png)

This only started happening fairly recently, within the past 3 weeks I think. The selection outlines appear for a split second after I have released my mouse button (once I have chosen the selection of the screen to take a picture of), and the screenshot is taken in that very brief moment in time. I'm using Ubuntu 16.04. Also, it doesn't matter if I make a selection very quickly or if I wait 5 seconds to release my mouse button.

**Comment by jomo** [comment]
See #32
