### ISSUE TITLE
white line

### ISSUE THREAD

**Issue by ralpheeee88** [jomo/imgur-screenshot#77]
https://i.imgur.com/BMSJ3vi.png

I keep getting a white line every time take a pic.... the dimension of the white line generally remains the same however the position of the line is random...

(i just noticed while looking at the pic again it could do with the fact i dragged a selection, paused the drag, then continued to get a full screen  pic.....hope that makes sense....)

**Comment by Brottweiler** [comment]
Read https://github.com/jomo/imgur-screenshot/issues/32 and https://github.com/jomo/imgur-screenshot/issues/75
