### ISSUE TITLE
Failed to take screenshot error - none of the Troubleshooting issues applies imho

### ISSUE THREAD

**Issue by Maxiride** [jomo/imgur-screenshot#78]
Hello, I recently installed this little software on my Arch Linux laptop. Whenever running the script it simply fails and suggest me to check the wiki page.

I do not press any key while selection, furthermore the selection doesn't even show up. The lines I pasted from the terminal are outputted instantly just after hitting enter to execute the command.

```
[federico@arch-anywhere-federico]: ~>$ imgur-screenshot -u
Version v1.7.4 is up to date.
[federico@arch-anywhere-federico]: ~>$ imgur-screenshot
Please select area
Failed to take screenshot 'imgur-2016_06_25-11:28:55.png': ''. For more information visit https://github.com/jomo/imgur-screenshot/wiki/Troubleshooting
[federico@arch-anywhere-federico]: ~>$ 
```

**Comment by jomo** [comment]
Please run with `--debug` as the first argument

**Comment by Maxiride** [comment]
Here it is: [crash.txt](https://github.com/jomo/imgur-screenshot/files/333060/crash.txt)

**Comment by jomo** [comment]
scrot returns a 127 status. From the bash manual:

> If a command is not found, the child process created to execute it returns a status of 127

I assume you have scrot configured as screenshot tool (the default) but don't have it installed.
