### ISSUE TITLE
Terminal window gets in the way . . 

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [jomo/imgur-screenshot#84]
. . and clicking its minimize button makes your script try to trigger the screenshot!

Thanks for the program, which is much needed, at least on Linux Mint, because the other programs that do this . . no longer work. However, can't we have a version of the program that can run without a terminal window open, or that at least allows one to get the window out of the way?

Also, allowing an easy way to allow manual deletion of the images - i.e. providing the imgur deletion URL - would be good (although perhaps there is a way of discovering that URL that I don't know).

Thanks.

Linux Mint 18 x64 Cinnamon.

**Comment by jomo** [comment]
0. this is a bash script, it doesn't interact with terminal windows at all. If you run from terminal, prepend `sleep 5` or something like that so you have a 5 second delay to minimize the window.
0. The script actually prints out the deletion URL right after the image URL, [see here](https://github.com/jomo/imgur-screenshot/blob/89526dd301771a48777496abbadb9e2fc61865f0/imgur-screenshot.sh#L329-L330).
