### ISSUE TITLE
Configurable notification duration

### ISSUE THREAD

**Issue by ghost** [jomo/imgur-screenshot#85]
At the moment notification duration is hardcoded at 500 milliseconds. It would be great if that could be a config option.

**Comment by jomo** [comment]
Has been addressed in #80. I'm quite busy these days but I'll merge it in soon™

**Comment by laur89** [comment]
@torpet tried to fix it with #62 (still hard-coded change instead of config opts), but that PR received 0 attention.

**Comment by jomo** [comment]
No worries, I'll address all open PRs eventually, I'm just quite busy.

**Comment by vienthet** [comment]
Can you also add taking screenshot of the entire page with print screen when running the script?

**Comment by jomo** [comment]
Fixed in 4fcca21ca3b4bb28668f56d037f1160291ae1310
