### ISSUE TITLE
Automating imgur-screenshot

### ISSUE THREAD

**Issue by hex3r** [jomo/imgur-screenshot#87]
Hey there, I wanted to know if it's possible to make the program do the following. I'm new to OS X but I'm learning quickly so just point me in the right direction, if possible:

1. Press a hotkey to capture an area / fullscreen
2. Draw lines, add text if necessary, confirm
3. Have the program upload the captured and edited image to imgur and copy the direct link to buffer

Currently the program in its current state is only executed from the command line, it does not let me edit the image and it opens the direct link to the image (which I don't need).

Ideally I just want to press a hotkey, mark the area, edit if necessary and then paste the link somewhere. No pop-ups except what's needed.

**Comment by jomo** [comment]
0. You can use a 3rd party tool to bind the script to key. It's also possible to do this native with OS X but requires writing some apple specific files, you'd need to look that up
0. I think you're looking for the `edit` config option. You can edit the screenshot with Photoshop, Gimp, or even ImageMagick or whatever you like.
0. That's what it does anyway :)

**Comment by hex3r** [comment]
Thank you!

1. Okay, managed to do that with OS X native Automator (AppleScript).
2. How do I set what software I want to use for editing?

**Comment by hex3r** [comment]
I've tried launching with
`imgur-screenshot.sh -i seashore ~/Pictures/%img` 
but it throws me
`file '/Users/.../Pictures/%img' doesn't exist !`

Why doesn't it take %img as a variable of the image?

**Comment by jomo** [comment]
You're only passing `seashore` as an argument to the `-i` flag. Try quoting the whole thing, so the argument doesn't end at the space.

**Comment by hex3r** [comment]
Thanks @jomo for getting back to me with a reply, I've managed to do what I wanted. I wrote two native OS X AppleScripts - one just captures the selection, instantly uploads it to imgur and copies the link to the buffer and the other one does the same with an image edit step. I've also bound them to hotkeys natively. Awesome!

**Comment by jomo** [comment]
I think the wiki would be a good place for these kind of things
