### ISSUE TITLE
Feature request: instant fullscreen capture (no selection)

### ISSUE THREAD

**Issue by hex3r** [jomo/imgur-screenshot#88]
I think would be nice if there was a console option to make a fullscreen screenshot instead of having to drag the selection all around the screen.

**Comment by jomo** [comment]
We already have this, you can run the script with `-f` or `--full`. I just missed to add that to the README. #62 adds that to the README but I have yet to merge it.

**Comment by hex3r** [comment]
Also pointing out that it's not included in the description if you launch the program with `--help` parameter.
