### ISSUE TITLE
Changing image name format?

### ISSUE THREAD

**Issue by hex3r** [jomo/imgur-screenshot#90]
I'm using an image editor I found to be the best lightweight one for OS X (Skitch) and there's a small issue with it that it always converts all spaces or symbols (in case of imgur-screenshot, **slashes**) to underscores when saving an edited image. This is slightly annoying as it's basically asking for another senseless action from the user.

While I have appealed to Skitch about changing this policy, I have my doubts that they would be willing to change anything in their software already in production as a relatively big company.

So I was wondering whether there's a way to make imgur-screenshot save images with underscores in their names, not slashes. Example image of what I'm talking about below.

https://i.imgur.com/meSizeb.png

**Comment by jomo** [comment]
See the `file_name_format` [config option](https://github.com/jomo/imgur-screenshot/wiki/Config).

**Comment by hex3r** [comment]
@jomo I've installed imgur-screenshot with brew and the imgur-screenshot is not present in ~/.config. =

**Comment by jomo** [comment]
You can just copy it there

**Comment by hex3r** [comment]
I see some settings there that I set as command-line arguments. Do my command-line arguments override those in the file? Sorry if it's a noob question.

**Comment by jomo** [comment]
yes, the config file specifies the default action and you can use CLI to override them.

**Comment by hex3r** [comment]
I think there's a bug that occurs when I create this settings.conf file without editing it. The script just stops working. I've tried launching the default, untouched imgur-screenshot.sh from the console right after I created the default settings.conf file and it throws an error.

**Comment by jomo** [comment]
Can you with `--debug` as the first option and paste the output + config file in a new issue?
