### ISSUE TITLE
Album Privacy

### ISSUE THREAD

**Issue by lewiseason** [jomo/imgur-screenshot#92]
The imgur API allows you to set an album's privacy to one of public/hidden/secret - it would be neat if I could specify this on the command line.

**Comment by jomo** [comment]
The idea of this tool is that you upload images and get a link to share them. I think defining the privacy at the CLI would be quite uncommon.

You can either set the default privacy level on your [account settings](https://imgur.com/account/settings/) or change it via the website after uploading.

Unless more people vote for this feature, I'm probably not going to add it, sorry.

**Comment by lewiseason** [comment]
The reason it'd be handy on the CLI is that I can bind different keyboard shortcuts to "take a findable screenshot" and "take a screenshot that can only be viewed if you know the link". This is doubly handy if you don't have an imgur account.

No worries if you think this is out of scope, however.
