### ISSUE TITLE
use imgur names

### ISSUE THREAD

**Issue by nkh** [jomo/imgur-screenshot#93]
imgu provides:
user name/account URL
Client ID
Client Secret

imgur-screenshot has:
imgur_anon_id=""
imgur_acct_key=""
imgur_secret=""

my guess was the mapping below but the images get uploaded to imgur but not my account

imgur_anon_id=Client ID
imgur_acct_key=user name
imgur_secret=Client Secret

**Comment by jomo** [comment]
The meaning of the options is documented [on the wiki](https://github.com/jomo/imgur-screenshot/wiki/Config).

To check / connect your imgur account run `imgur-screenshot -c`, then upload using `-l true`.

**Comment by nkh** [comment]
I got:

Woah there!
The information you sent wasn't quite correct. Please return to the place that sent you to this page and try again.

but I go registred an application with anonymous access, I guess that I have to one with oauth2 acces, right?

**Comment by jomo** [comment]
```shell
$ imgur-screenshot.sh -c
In order to upload to your account, register a new application at:
https://api.imgur.com/oauth2/addclient
Select 'OAuth 2 authorization without a callback URL'
Then, set the imgur_acct_key (Client ID) and imgur_secret in your config.
```
