### ISSUE TITLE
The requested URL returned error: 429

### ISSUE THREAD

**Issue by milandamen** [jomo/imgur-screenshot#94]
When I try to use the tool I get this error:

```
Upload failed: "curl: (22) The requested URL returned error: 429"
```

I tried it at different times during the day, and it never works. It stopped working a few days ago.

**Comment by thetarkus** [comment]
Get an anonymous API key here: https://api.imgur.com/oauth2/addclient

In terminal, create the overrides directory and write the new key to settings.conf inside of it.
```
mkdir ~/.config/imgur-screenshot
echo "imgur_anon_id=$NEW_API_KEY" > ~/.config/imgur-screenshot/settings.conf
```

Just be sure to replace `$NEW_API_KEY` with the new key you just generated.

**Comment by jomo** [comment]
This is the message it prints out:
```json
{
    "data": {
        "error": "Daily client requests exceeded",
        "method": "POST",
        "request": "/3/image"
    },
    "status": 429,
    "success": false
}
```

The app was previously whitelisted and limits were only counted per IP address. Unfortunately, imgur [removed application whitelisting](https://github.com/jomo/imgur-screenshot/issues/67#issuecomment-204771073).

----

As a workaround, you can upload to your account (images are not public by default) or register an application for anonymous usage. However **this does require an imgur account**.

![screenshot](https://cloud.githubusercontent.com/assets/3585743/18726513/1a282b94-8045-11e6-9579-7718a504fa0e.png)
![screenshot](https://cloud.githubusercontent.com/assets/3585743/18726712/fa98d50c-8045-11e6-8b7c-aa1b3c7ae7ea.png)

Now replace the `imgur_anon_id` option in your config with the "Client ID".

(As @thetarkus already pointed out while I was writing this 👍)

----

If this issue lasts longer than a couple days (or reoccurs) I'll try to contact imgur and hopefully get it sorted out.
