### ISSUE TITLE
Is it possible to upload screenshots privately?

### ISSUE THREAD

**Issue by hex3r** [jomo/imgur-screenshot#95]
Some of the screenshots I'm making might contain sensitive data so I was wondering whether it's possible to upload the screenshots to Imgur privately so nobody would see them.

I know about the auto-delete option but that's not exactly what I'm after.

**Comment by jomo** [comment]
imgur-screenshot defaults to anonymous uploads (though these may fail atm, see #94).

**Comment by hex3r** [comment]
@jomo Does anonymous equal private in this term? Are those screenshots hidden from view?

**Comment by jomo** [comment]
Images aren't published to the gallery, you will need the link to access images in *any* case.
