### ISSUE TITLE
Action right after screenshot is taken

### ISSUE THREAD

**Issue by Tithen-Firion** [jomo/imgur-screenshot#98]
I wanted to play sound right after taking screenshot. Right now I'm using `edit_command` for this:

```
edit_command="paplay .camera.wav &"
edit="true"
```

 It doesn't seem right because when I want to use editor I can't just use `-e true`. I have to insert whole command, for example `-i "paplay .camera.wav & gimp %img"`.

**Comment by jomo** [comment]
Sorry for the (very) late response. You should be able to achieve this by using something like this:
```shell
screenshot_select_command="scrot -s %img && paplay .camera.wav"
```
